server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/navdata
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO